name: Code Layout
on: [push]
jobs:
  code_style:
    if: ( github.repository == 'MerginMaps/mergin-cpp-client' )
    runs-on: ubuntu-latest
    steps:
      - name: Install astyle
        run: |
          sudo apt-get install astyle

      - uses: actions/checkout@v2

      - name: Run astyle check
        run: |
          ./scripts/check_all.bash
