name: Linux Build
on: [push]
env:
  TEST_MERGIN_URL: https://test.dev.merginmaps.com/
  TEST_API_USERNAME: test_inputapp
  TEST_API_PASSWORD: ${{ secrets.MERGINTEST_API_PASSWORD }}
  QT_VERSION: '5.14.2'
  CACHE_VERSION: 1
  GEODIFF_VERSION: 1.0.6
  
concurrency:
  group: ci-${{github.ref}}-linux
  cancel-in-progress: true
  
jobs:
  linux_build:
    if: ( github.repository == 'MerginMaps/mergin-cpp-client' )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mergin-cpp-client
        uses: actions/checkout@v2
        with:
          path: mergin-cpp-client

      - name: Checkout input
        uses: actions/checkout@v2
        with:
          repository: MerginMaps/input
          path: input

      - name: Checkout geodiff
        uses: actions/checkout@v2
        with:
          ref: ${{ env.GEODIFF_VERSION }}
          repository: MerginMaps/geodiff
          path: geodiff

      - name: Install Deps
        run: |
          sudo apt-get install cmake

      - name: Cache Qt
        id: cache-qt
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: ${{ github.workspace }}/Qt
          key: ${{ runner.os }}-QtCache-v1-${{ env.QT_VERSION }}-${{ env.CACHE_VERSION }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ env.QT_VERSION }}
          dir: ${{ github.workspace }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          
      - name: build geodiff
        run: |
          mkdir -p build-geodiff
          cd build-geodiff

          cmake \
            -DCMAKE_BUILD_TYPE=Debug \
            -DENABLE_TESTS=FALSE \
            ../geodiff/geodiff

          make
          sudo make install

      - name: build mergin-cpp-client
        run: |
          cp mergin-cpp-client/scripts/ci/config.pri mergin-cpp-client/src/config.pri
          mkdir -p build-mergin-cpp-client
          cd build-mergin-cpp-client

          $Qt5_DIR\qmake \
            ../mergin-cpp-client/src/client.pro \
            CONFIG+=debug

          make

      - name: run mergin tests
        run: |
          cd build-mergin-cpp-client/
          LD_LIBRARY_PATH=../build-geodiff:$LD_LIBRARY_PATH ./mergin --help
